print("enter name")
character_name=input()
print("enter age")
character_age=input()
print("there once was a man named "+character_name+",")
print("he was "+character_age+ " years old.")
print("he really liked the name "+character_name+",")
print("but didnt like being "+character_age+".")